### ISSUE TITLE
VSCode plugin compatibility problerm

### ISSUE THREAD

**Issue by captainliuy** [veryl-lang/veryl#1004]
In my development environment, the newest version of VSCode I can install is 1.70.3. The veryl plugin does not support this version of VSCode. Is it possible for it to be backward compatible?

**Comment by dalance** [comment]
The current supported version (`^1.74.0`) is meaningless, it is only a version at which I started to develop.
So I think the supported version can be decreased.

I don't know precise minimum required version of VSCode, but it probably is 1.51.0 according to 
https://github.com/Microsoft/vscode-python/issues/15237 .
