### ISSUE TITLE
Refer variable which is not assigned yet

### ISSUE THREAD

**Issue by taichi-ishitani** [veryl-lang/veryl#1028]
A variable should be assigned before it is referred to get correct simulation result.

```systemverilog
// OK
always_comb {
  a = 1;
  b = a;
}

// NG
always_comb {
  d = c;
  c = 1;
}
```

Veryl should report an error fo this kind of code but currently not.
![image](https://github.com/user-attachments/assets/9fb0e520-270a-4456-8a6f-c2811d21fb77)

**Comment by nananapo** [comment]
Instead of reporting error, I think it's better to sort automatically by Veryl compiler. (or create option)
Reordering manually to make the simulation work correctly is only for simulation and is not a essential task.

**Comment by nananapo** [comment]
hmm....
reordering maybe difficult when there are if or case in always_comb😞
