### ISSUE TITLE
Avoid `Warning-DECLFILENAME` warning reported by Verilator

### ISSUE THREAD

**Issue by taichi-ishitani** [veryl-lang/veryl#1155]
Verilator reports a `Warning-DECLFILENAME` warning because verilator requires consistency between module name and file name but Veryl add the project prefix to module name.
https://qiita.com/mikecat_mixc/items/cf98dffa4891f00f132f#hello-world

I think it would be nice to add the `/* verilator lint_off DECLFILENAME*/` and `/* verilator lint_on DECLFILENAME*/` pragma comments to head and tail of generated SV files to avoid this warning.

**Comment by dalance** [comment]
I think such tool-specific features should be optional at least.
And the need is questionable because there are many workarounds like below:

* Use `omit_project_prefix = true`
* Don't add `-Wall` to Verilator
* Add `-Wno-DECLFILENAME` to Verilator

**Comment by taichi-ishitani** [comment]
OK, I understand. I'm closing this ticket.
