### ISSUE TITLE
[質問] キャストについてなど

### ISSUE THREAD

**Issue by ryuz** [veryl-lang/veryl#176]
Veryl 活用させて頂いております。 質問ばかりで恐縮なのですが。

### キャストについて

型のキャストについて

```
assign a = b as logic<12>;
assign c = d as u32;
```

などはできないのでしょうか？

localparam などで type を作れば問題ないのですが、int  にはキャストできたりするようなのでポリシーを知れると嬉しいです。

### 左辺での連接演算子

```
assign a = {b, c};
```

はできるようですが

```
assign {a, b} = c;
```

は、できないようですが、意図的に禁止されているものでしょうか？

**Comment by dalance** [comment]
> 型のキャストについて

少なくとも `u32` はできるべきですね。
`logic` もできますが、 `logic<12>` は SystemVerilog の仕様上不可能です。

> int にはキャストできたりするようなのでポリシーを知れると嬉しいです。

intというのは組み込み型としては存在しないので、外部のユーザ定義型扱いで通っていると思います。

> 意図的に禁止されているものでしょうか？

意図的ではありませんでしたが、追加するとなると構文上の負荷は高そうです。
要検討かと思います。

**Comment by ryuz** [comment]
ご回答ありがとうございます。

> logic もできますが、 logic<12> は SystemVerilog の仕様上不可能です。

承知いたしました(なんとなく想像はできます)。

Verilator の 幅チェックが割とうるさく、ビット幅変換によく bit 幅だけ指定したキャストを使っていて、使いたくなった次第です。
(特に bit 幅を増やす方向がきちんと書くと少し面倒ですので)。

回避手段はあるので、特に問題はありません。
理由が知れてすっきりしました、ありがとうございます。

**Comment by taichi-ishitani** [comment]
```systemverilog
a = 4'(b);
```

みたいな、幅キャストは対応してましたっけ？

**Comment by taichi-ishitani** [comment]
幅キャストが実装されれば、代入幅不一致問題は解決出来そうですね。

> a = b as 4;
> a = b as <4>;

どちらでもよいと思うのですが、後者ですと多次元配列へのキャストもできそうに見えてしまうのが、少々難点ではあります（大した問題にはならないと思いますが）。

**Comment by dalance** [comment]
> どちらでもよいと思うのですが、後者ですと多次元配列へのキャストもできそうに見えてしまうのが、少々難点ではあります（大した問題にはならないと思いますが）。

前者だとなんのキャストかよくわからない気がしたので後者かなと思いましたが、多次元指定できてしまうのは確かにそうですね。

**Comment by dalance** [comment]
というかSystemVerilogのキャストが普通の意味の型キャストではなくて、もっといろいろな変換ができてしまう感じなのですよね。
ちょっと全体的に整合性が取れるよう考え直した方がいいかもしれません。

**Comment by taichi-ishitani** [comment]
> 多次元配列へのキャスト

SystemVerilog 的には、packed であれば型が何であれ代入は可能なので、

```
a = b as <2>;
c = d as <2, 3>;
e = f as foo_struct;
g = h as foo_struct <2, 3>
```

のようなコードを、

```systemverilog
a = (2)'(b);
c = (2*3)'(d);
e = foo_struct'(f);
g = ($bits(foo_struct)*2*3)'(h);
```

の様に変換するのはありかもですね。

**Comment by dalance** [comment]
組み込み型へのキャストについては#499 にあるのでこちらはクローズします。
