### ISSUE TITLE
[Feature] Repalce `parameter` and `localparam` keywords

### ISSUE THREAD

**Issue by taichi-ishitani** [veryl-lang/veryl#537]
The `parameter` and `localparam` keywords are relatively long keywords.
So I'd like to propose alternative words instead of these keywords.

* `param`
    * replacement of `parameter` keyword
* `const`
    * replacement of `localparam` keyword

I feel good appearance because these words have same length.

```systemverilog
module ModuleA #(
    param ParamA: u32 = 10,
    const ParamB: u32 = 10
)
```

**Comment by nblei** [comment]
I am not a fan of this suggestion.

In many languages, `const` simply means that a variable cannot have its value modified.  A `localparam`, on the other hand, must be statically evaluable.

**Comment by dalance** [comment]
In this context, `const` seems to mean "evaluated as constant value at compile time" like `constexpr` of C++.
But I agree the meaning of `const` is confusable because it is used through many languages by several meanings.

For example, `param` / `local` may be more familiar to SystemVerilog users?

```systemverilog
module ModuleA #(
    param ParamA: u32 = 10,
    local ParamB: u32 = 10
)
```

**Comment by taichi-ishitani** [comment]
> param / local

I agree with this suggestion.
