### ISSUE TITLE
LoLa (Logic Language) references

### ISSUE THREAD

**Issue by andreas-kupries** [veryl-lang/veryl#560]
From the HN about veryl:

> (Rochus) appreciated e.g. in Wirth's Lola-2 HDL ...

Links:
- https://www.google.com/search?q=wirth+lola
- https://people.inf.ethz.ch/wirth/Lola/index.html
- https://en.wikipedia.org/wiki/Lola_(computing)
- http://pascal.hansotten.com/niklaus-wirth/lola/
- https://github.com/rochus-keller/Lolac
- https://web.archive.org/web/20060117175059/http://www.cs.inf.ethz.ch/~wirth/books/DigitalDesign/
- https://oberoncore.ru/_media/library/eberle_gehring_ludwig_wirth_tools_for_digital_circuit_design_using_fpga.pdf

**Comment by dalance** [comment]
Thanks!
I'll check it later.
