### ISSUE TITLE
Support wavedrom markdown in Veryl

### ISSUE THREAD

**Issue by saturn77** [veryl-lang/veryl#597]
The Rust library mdbook-wavedrom allows for inserting wavedrom descriptions into document. 

This is a feature request to support this crate with Veryl. 

https://github.com/JasMoH/mdbook-wavedrom

So for example, inside of some comments within a module: 

/*

```wavedrom
{signal: [
  {name: 'clk', wave: 'p.....|...'},
  {name: 'dat', wave: 'x.345x|=.x', data: ['head', 'body', 'tail', 'data']},
  {name: 'req', wave: '0.1..0|1.0'},
  {},
  {name: 'ack', wave: '1.....|01.'}
]}
```

*/

Would have this image inserted into the html, upon running Veryl doc 

![image](https://github.com/veryl-lang/veryl/assets/5698048/8334894f-400a-45a4-927e-5990c1b72a7a)

**Comment by dalance** [comment]
I've implemented wavedrom integration.
It's very good feature!

![image](https://github.com/veryl-lang/veryl/assets/4331004/e5e3f447-3b81-44f1-9c57-3983aefdeb64)
