### ISSUE TITLE
Cannot find member variable from struct input port

### ISSUE THREAD

**Issue by taichi-ishitani** [veryl-lang/veryl#603]
Veryl reports an error unexpectedly for member reference of struct input port.
You can repdoduce this error by building following code.

```systemverilog
package foo_bar_baz_pkg {
  struct foo_bar_baz_type{
    foo: logic,
    bar: logic,
    baz: logic
  }
}

module foo_bar_baz (
  i_foo_bar_baz: input foo_bar_baz_pkg::foo_bar_baz_type,
  o_foo: output logic,
  o_bar: output logic,
  o_baz: output logic
){
  assign o_foo = i_foo_bar_baz.foo;
  assign o_bar = i_foo_bar_baz.bar;
  assign o_baz = i_foo_bar_baz.baz;
}
```

![image](https://github.com/veryl-lang/veryl/assets/2922232/81003000-6e82-4588-9f00-60df0ea39ac5)

**Comment by dalance** [comment]
This seems to be resolved at master branch.

**Comment by taichi-ishitani** [comment]
Thank you!
I've confirmed this issue is resolved.
