### ISSUE TITLE
Incorrect behavior for hierarchical identifiers for nested structures within modports

### ISSUE THREAD

**Issue by anantajit** [veryl-lang/veryl#628]
Note: this is a similar issue to #541

I'm running Veryl v0.8.2, with the following design:

```
package pkg {
  struct DataStruct {
    test: logic<32>,
  }
}

interface X {
    var data: pkg::DataStruct;

    modport port {
      data: input
    }
}

module Y (
  dataport: modport X::port
) {

  assign dataport.data.test = 32'h23;

}

```

This is met with the error `Error: unknown_member (link)`, which appears to be a bug. Note that the snippet below passes `veryl check`:

```
package pkg {
  struct DataStruct {
    test: logic<32>,
  }
}

interface X {
    var data: pkg::DataStruct;

    modport port {
      data: input
    }
}

module Y (
  dataport: modport X::port
) {

  var datav: pkg::DataStruct;
  assign datav.test = 32'h23;

  assign dataport.data = datav;

}
```

**Comment by nblei** [comment]
@dalance I think it is likely that there are many corner cases involved in the whole namespace/symbol-table/scoping resolution stuff.  Perhaps it may be time to rethink the symbol table design?

**Comment by dalance** [comment]
@nblei Thank you for your suggestion. I found many obsolete code related to SystemVerilog namespace, so I'll refactor them and fix this issue at the same time.
