### ISSUE TITLE
[Question] How to use case statement with don't care?

### ISSUE THREAD

**Issue by nananapo** [veryl-lang/veryl#641]
Hi.
Is the case statement with don't care like ```casez``` or ```casex``` supported?
I want to use it to implement a decoder.

**Comment by taichi-ishitani** [comment]
Veryl has not yet supported these statement.

@dalance 
SystemVerilog has `case inside` statement that is enhanced version of `casex` statement.
So I think Veryl should support `case inside` but has not to support `casex` and `casez` statements.

**Comment by nananapo** [comment]
By the way, case expression seems to be converted into logic using ternary operator ```?```. But I think converting into case statement is better.

**Comment by dalance** [comment]
> By the way, case expression seems to be converted into logic using ternary operator `?`. But I think converting into case statement is better.

The reason using ternary operator is that it can be used at arbitrary expression context like below:

```systemverilog
// pass
localparam A = X == 1 ? 0 : 1;

// fail
localparam A = case (X)
    1: 0;
    default: 1;
endcase
```

**Comment by nananapo** [comment]
I think it would be nice if the semantics of case expression and statement are not different.

**Comment by taichi-ishitani** [comment]
SystemVerilog does not have `if expression` and `case expression` features so I think it's difficult.

**Comment by taichi-ishitani** [comment]
@nananapo ,
I changed emmition of `case` statemen from the simple `case` statement to the `case inside` statement.
Now you can use unknown values for case conditions like the `casex` statement.

**Comment by nananapo** [comment]
やったー😆
ありがとうございます🙏

2024年6月14日(金) 18:03 Taichi Ishitani ***@***.***>:
