### ISSUE TITLE
[Feature] Add option/configuration to follow symlinks.

### ISSUE THREAD

**Issue by ciniml** [veryl-lang/veryl#651]
Currently, `veryl build` does not follow symlinks when gathering the source files. 

https://github.com/veryl-lang/veryl/blob/82435188b958bd61ceafef9c246e3f8b9a3a3e7c/crates/metadata/src/utils.rs#L6

So I'm currently using modified version of `veryl` which follows symlinks like this.

```rust
pub fn gather_files_with_extension<T: AsRef<Path>>(
    base_dir: T,
    ext: &str,
) -> Result<Vec<PathBuf>, MetadataError> {
    let mut ret = Vec::new();
    for entry in WalkDir::new(base_dir).follow_links(true) {
        let entry = entry?;
        if entry.file_type().is_file() {
            if let Some(x) = entry.path().extension() {
                if x == ext {
                    debug!("Found file ({})", entry.path().to_string_lossy());
                    ret.push(entry.path().to_path_buf());
                }
            }
        }
    }
    Ok(ret)
}
```

In my use case, it's fine to just follow symlinks, but for practical purposes, I think it's a good idea to make it possible to enable or disable this feature through options or configuration files.

**Comment by dalance** [comment]
I think symlink support can be enabled by default for local usage.
The problem about symlink is that some platform (e.g. Windows) may not support symlink at git checkout.
So `veryl publish` will check symlink and deny them.
