### ISSUE TITLE
import declaration before module port declaration

### ISSUE THREAD

**Issue by nananapo** [veryl-lang/veryl#681]
```systemverilog
package package_name {
  type T = logic<32>;
}
module module_name
    import package_name::*;
#()(
    value : input T
){}
```

**Comment by taichi-ishitani** [comment]
You can write `package import` like this.
https://github.com/taichi-ishitani/pzbcm_veryl/blob/89749d7b2adeba638a40af60567ee216befe57f7/pzbcm_fifo/pzbcm_fifo.veryl#L1

@dalance ,

It seems that there are no documentations for `package import`.

**Comment by dalance** [comment]
I removed import declaration after module name to reduce syntax complexity.
Instead of it, file scope import can be used.
I'll write the document later.

**Comment by nananapo** [comment]
Thanks
