### ISSUE TITLE
Veryl doesn't emit package_scope

### ISSUE THREAD

**Issue by nananapo** [veryl-lang/veryl#692]
config.veryl
```veryl
package config {
    local XLEN: u32 = 32;
}
```
eei.veryl
```
package eei {
    local XLEN: u32 = config::XLEN;
}
```

eei.veryl is translated into 
```systemverilog
package core_eei;
    localparam int unsigned XLEN = XLEN;
endpackage
```

Veryl doesn't emit package scope when package parameter refers another same name package value.

**Comment by dalance** [comment]
This issue was fixed at #726 which changes visibility detection mechanism of emitter.
