### ISSUE TITLE
Comments following embed declaration cause syntax error

### ISSUE THREAD

**Issue by clkbug** [veryl-lang/veryl#733]
Hi.
It appears that comments are not permitted following an `embed` declaration.

For example:

```veryl
module Module47 {}

embed (inline) sv{{{
module test;
   initial begin
       $display("hello");
   end
endmodule
}}}

// this comment causes
// > Error: ParserError::SyntaxError
// > × Unexpected token: 'comment'

```

Is this a grammar definition error?

**Comment by dalance** [comment]
> Is this a grammar definition error?

Yes. I missed the comment definition after embed declaration.
