### ISSUE TITLE
VSCode extension failed to restart veryl-ls

### ISSUE THREAD

**Issue by clkbug** [veryl-lang/veryl#734]
Hi.
Executing "vscode-veryl: Restart language server" command causes this error.

> command 'vscode-veryl.restartServer' not found

The error appears to be due to a mismatch of command names in the following two files.

In `support/vscode/src/extension.ts:70`:

```typescript
	context.subscriptions.push(
		commands.registerCommand("vscode-veryl.restartVerylLs", () => {
			stopServer().then(function () {startServer(context);}, startServer);
		})
	);
```

In `support/vscode/package.json:28`:

```json
  "contributes": {
    "commands": [
      {
        "command": "vscode-veryl.restartServer",
        "title": "Restart language server",
        "category": "vscode-veryl"
      }
    ],
```

**Comment by dalance** [comment]
Thanks!
I'll fix it.
