### ISSUE TITLE
Merge parameter and generics

### ISSUE THREAD

**Issue by dalance** [veryl-lang/veryl#912]
Currently there are two way for specifing parameter at instantiation: parameter and generics, and the syntax is separated completely.
Merging these syntax may enhance languate consistency. On the other hand, the current syntax may be good because of emphasizing the differences between parameter and generics.

* From

```systemverilog
module ModuleA::<T: Proto> #(
    param A: u32 = 1,
) {
    function FuncA::<T: const> (
        a: input logic
    ) -> logic {
    }

    let x: logic = FuncA::<1>(1);

    inst u: ModuleB::<T> #(
        A: 1,
    ) (
    );
}
```

* To

```systemverilog
module ModuleA #(
    T: generic Proto,
    A: param u32 = 1,
) {
    function FuncA #(
        T: generic const
    ) (
        a: input logic
    ) -> logic {
    }

    let x: logic = FuncA #(T: 1)(1);

    inst u: ModuleB #(
        T,
        A: 1,
    ) (
    );
    
}
```

**Comment by taichi-ishitani** [comment]
Resolving timing of these elements are different.

* Generics: SV generation phase @ Veryl
* Parameter: Elaboration phase @ other tools

Therfore, I think it is consusable if these elements can be declaraed at the location and these should not be merged.
